import React, { useState } from 'react';
import { DeploymentConfig } from '../types';
import { CheckIcon, CopyIcon, DownloadIcon } from './Icon';

interface WorkflowPreviewProps {
  config: DeploymentConfig;
}

const WorkflowPreview: React.FC<WorkflowPreviewProps> = ({ config }) => {
  const [copied, setCopied] = useState(false);

  // Path Logic
  const normalizedRemoteBase = config.remoteBase.endsWith('/') ? config.remoteBase : `${config.remoteBase}/`;
  const fullRemotePath = config.target === 'root' 
    ? normalizedRemoteBase 
    : `${normalizedRemoteBase}${config.targetName}/`;

  // Auth Block
  const authBlock = config.authType === 'password'
    ? `          username: \${{ secrets.FTP_USER }}
          password: \${{ secrets.FTP_PASSWORD }}`
    : `          username: \${{ secrets.FTP_USER }}
          ssh-private-key: \${{ secrets.SSH_PRIVATE_KEY }}`;

  // Protocol Block
  const defaultPort = config.protocol === 'sftp' ? '22' : '21';
  const port = config.ftpPort || defaultPort;
  
  const protocolSettings = config.protocol === 'sftp' 
    ? `          protocol: sftp
          port: ${port}` 
    : `          protocol: ftp
          port: ${port}`;

  // Strategy Logic
  const cleanFlag = config.deploymentMode === 'add' ? 'false' : 'true';

  // Dynamic Name
  const workflowName = `Deploy ${config.target === 'root' ? 'Site Root' : config.targetName}`;

  // Log Script
  const logScript = config.createLog
    ? `
      - name: 📝 Update Registry (Log)
        run: |
          echo "[$(date -u)] DEPLOY: \${{ github.sha }} | REF: \${{ github.ref }} | MODE: ${config.deploymentMode.toUpperCase()}" >> deploy_log.txt
          # Uploading log file specifically before main sync
`
    : '';

  // Excludes
  const defaultExcludes = [
      "**/.git*",
      "**/.git*/**",
      "**/node_modules/**",
      ".gitignore",
      ".env",
      ".env.local",
      "README.md",
      "LICENSE"
  ];
  
  if (config.target === 'root') {
      defaultExcludes.push("wp-config.php");
      defaultExcludes.push(".htaccess");
      defaultExcludes.push("wp-content/uploads/**");
  }

  // Webhook Notification Step
  const webhookSteps = config.webhookUrl ? `
      - name: 🔔 Webhook Notify (Success)
        if: success()
        run: |
          curl -X POST -H "Content-Type: application/json" \\
          -d '{"status": "success", "project": "'"\${{ github.repository }}"'", "commit": "'"\${{ github.sha }}"'", "ref": "'"\${{ github.ref }}"'"}' \\
          "${config.webhookUrl}"

      - name: 🚨 Webhook Notify (Failure)
        if: failure()
        run: |
          curl -X POST -H "Content-Type: application/json" \\
          -d '{"status": "failure", "project": "'"\${{ github.repository }}"'", "commit": "'"\${{ github.sha }}"'", "ref": "'"\${{ github.ref }}"'"}' \\
          "${config.webhookUrl}"
` : '';

  const yamlContent = `name: ${workflowName}
# ---------------------------------------------------------------------
# Generated by WP Deploy Gen
# ---------------------------------------------------------------------
# Git Source: ${config.gitUrl || 'Not specified'}
# Target Type: ${config.target} (${config.repoDetails.language})
# Strategy: ${config.deploymentMode === 'sync' ? 'Smart Sync (Mirror)' : 'Safe Add (No Delete)'}
# ---------------------------------------------------------------------

on:
  push:
    branches:
      - ${config.branch}
${config.enableRollback ? `  workflow_dispatch:
    inputs:
      git-ref:
        description: 'Rollback to SHA/Tag'
        required: false
        default: '${config.branch}'` : ''}

jobs:
  web-deploy:
    name: 🚀 Deploy ${config.target}
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: \${{ github.event.inputs.git-ref || github.ref }}
${logScript}
      - name: 📂 Sync to Server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: \${{ secrets.SERVER_IP }}
${authBlock}
${protocolSettings}
          local-dir: ./
          server-dir: ${fullRemotePath}
          dry-run: ${config.dryRun}
          clean: ${cleanFlag}
          exclude: |
${defaultExcludes.map(e => `            ${e}`).join('\n')}
${config.notifications ? `
      - name: 🚨 Notify Failure
        if: failure()
        run: echo "::error::Deployment Failed. Check Action Logs."` : ''}
${webhookSteps}
`;

  const handleCopy = () => {
    navigator.clipboard.writeText(yamlContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([yamlContent], { type: 'text/yaml' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'main.yml';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="h-full flex flex-col bg-gray-900 dark:bg-[#0f1115] border-l border-gray-700 dark:border-gray-800">
      <div className="flex items-center justify-between px-6 py-4 bg-gray-800 dark:bg-[#161b22] border-b border-gray-700 dark:border-gray-800">
        <div>
            <span className="text-xs font-bold text-gray-400 uppercase tracking-widest">Main.yml Preview</span>
            {config.dryRun && <span className="ml-2 text-xs bg-yellow-500/20 text-yellow-500 px-2 py-0.5 rounded border border-yellow-500/30">DRY RUN ACTIVE</span>}
        </div>
        <div className="flex gap-2">
            <button 
                onClick={handleDownload}
                className="flex items-center gap-2 px-4 py-2 text-xs font-bold uppercase tracking-wider text-gray-300 hover:text-white bg-gray-700 hover:bg-gray-600 rounded transition-all"
            >
                <DownloadIcon className="w-4 h-4" />
                Download
            </button>
            <button 
                onClick={handleCopy}
                className="flex items-center gap-2 px-4 py-2 text-xs font-bold uppercase tracking-wider text-white bg-blue-600 hover:bg-blue-500 rounded transition-all shadow-lg shadow-blue-900/20"
            >
                {copied ? <CheckIcon className="w-4 h-4" /> : <CopyIcon className="w-4 h-4" />}
                {copied ? 'Copied' : 'Copy Code'}
            </button>
        </div>
      </div>
      <div className="flex-grow overflow-auto custom-scrollbar p-6">
        <pre className="text-sm font-mono leading-relaxed whitespace-pre font-ligatures">
          <code className="block text-gray-300">
            {yamlContent}
          </code>
        </pre>
      </div>
    </div>
  );
};

export default WorkflowPreview;